src/xtgeo/xyz/_xyz.py
src/xtgeo/xyz/_xyz_oper.py
src/xtgeo/xyz/points.py
src/xtgeo/xyz/polygons.py
tests/test_xyz/test_points_vs_other.py

Point snap

---

src/xtgeo/cxtgeo/clib/CMakeLists.txt
src/xtgeo/cxtgeo/clib/src/CMakeLists.txt
src/xtgeo/cxtgeo/clib/src/surf_slice_cube.c
src/xtgeo/cxtgeo/clib/src/surf_slice_cube_window.c

In a process of making a Windows port

Adapt to MSVC compiler (part * of N)

---

src/xtgeo/__init__.py
src/xtgeo/grid3d/_gridprop_etc.py
src/xtgeo/grid3d/grid_property.py
tests/test_grid3d/test_grid_property.py

Made it possible to add a GridProperty from a Grid instance; quick approach
Also a larger refactorisation was done

Empty prop made easy

---

src/xtgeo/surface/regular_surface.py

Relates to equinor/webviz-subsurface/issues/285

Non strict topology check should not give warning on different topology

---

src/xtgeo/grid3d/_gridprop_etc.py
src/xtgeo/grid3d/grid_property.py
src/xtgeo/well/_wellmarkers.py
src/xtgeo/well/well1.py
tests/test_grid3d/test_grid_property.py
tests/test_well/test_well.py
tests/test_well/test_well_to_points.py

* Create a gridproperty from existing grid property
* Fix a bug in in Well get_zonation_point()

Rms etc issues

---

HISTORY.md

Release 2.8.0

---

src/xtgeo/cube/_cube_roxapi.py
src/xtgeo/roxutils/roxutils.py

Roxapi seismic

---

src/xtgeo/surface/_regsurf_gridding.py
src/xtgeo/surface/_regsurf_oper.py
src/xtgeo/surface/regular_surface.py
tests/test_surface/test_regular_surface.py
tests/test_surface/test_regular_surface_vs_cube.py

Surf overloaf

---

src/xtgeo/surface/_regsurf_import.py

Fix pmd format issue

---

src/xtgeo/plot/xsection.py
src/xtgeo/well/well1.py

- Use short well names for wellcrossings
- Add options to show/hide names and drilled year of crossed wells.

xsection: Wellcrossings and well trajectory changes

---

HISTORY.md
src/xtgeo/grid3d/_grid_roxapi.py
src/xtgeo/grid3d/_gridprop_roxapi.py
src/xtgeo/grid3d/grid.py
src/xtgeo/grid3d/grid_property.py
tests/test_grid3d/test_grid.py

* Renaming subgrids
* Improved reading of facies from Roxar (split body vs facies)
* Added casting key

Fix subgrid gridprops issues roxarapi

---

requirements.txt
src/xtgeo/common/xtgeo_dialog.py
src/xtgeo/grid3d/_gridprop_import_eclrun.py

E300 restart issue

---

HISTORY.md
src/clib/xtg/grd3d_export_grdeclprop2.c
src/clib/xtg/libxtg.h
src/xtgeo/grid3d/_gridprop_export.py
src/xtgeo/grid3d/grid_property.py
tests/test_grid3d/test_grid_property.py

Added also a key so that the format can be set by user

Improve formats for grdecl property to_file()

---

src/clib/xtg/grdcp3d_cellvol.c
src/clib/xtg/libxtg.h
src/clib/xtg/x_3d_polyhedron.c
src/xtgeo/grid3d/_grid_etc1.py
src/xtgeo/grid3d/_grid_roxapi.py
src/xtgeo/grid3d/grid.py
tests/test_common/test_calc.py
tests/test_grid3d/test_grid.py
tests/test_grid3d/test_grid_vs_points.py

Method for computing total cell bulk in xtgeo. Almost identical volume as with RMS

Cell totalbulk

---

src/clib/xtg/surf_cube_attr_intv.c
src/clib/xtg/surf_stack_slice_cube.c
src/xtgeo/grid3d/_grid_roxapi.py
src/xtgeo/surface/_regsurf_cube_window_v2.py
tests/test_surface/test_surface_cube_attrs.py

Fix targeted to #439 
Also fixes and issue in communication between Roxar API and xtgeo

Fix surf cube slice issue grane

---

HISTORY.md
README.md
src/clib/xtg/grd3d_points_ijk_cells.c
src/clib/xtg/grdcp3d_cellvol.c
src/clib/xtg/grdcp3d_quality_indicators.c
src/clib/xtg/libxtg.h
src/clib/xtg/pol_chk_point_inside.c
src/clib/xtg/pol_do_points_inside.c
src/clib/xtg/x_3d_polyhedron.c
src/xtgeo/common/calc.py
src/xtgeo/grid3d/_grid_etc1.py
src/xtgeo/grid3d/grid.py
src/xtgeo/grid3d/grid_properties.py
src/xtgeo/xyz/points.py
tests/test_common/test_calc.py
tests/test_grid3d/test_grid.py
tests/test_grid3d/test_grid_vs_points.py
tests/test_xyz/test_points_poly.py

A number of improvements in particular on grid_quality parameteres and (experimental) get_bulk_volume()

Cellvol cellqual etc improvements

---

src/clib/xtg/x_vector_linint2.c
src/xtgeo/well/well1.py
src/xtgeo/xyz/_xyz_oper.py
src/xtgeo/xyz/polygons.py
tests/test_well/test_well.py
tests/test_xyz/test_points_poly.py

Fix issue fence verticalwell

---

src/clib/xtg/libxtg.h
src/clib/xtg/surf_resample.c
src/xtgeo/surface/_regsurf_oper.py
src/xtgeo/surface/regular_surface.py
tests/test_surface/test_regular_surface_resample.py

Issue 450 resample bug

---

.pre-commit-config.yaml
.pylintrc
setup.cfg
src/xtgeo/cube/__init__.py
src/xtgeo/cube/_cube_export.py
src/xtgeo/cube/_cube_import.py
src/xtgeo/cube/_cube_roxapi.py
src/xtgeo/cube/_cube_utils.py
src/xtgeo/cube/cube1.py
src/xtgeo/grid3d/_grid_etc1.py
src/xtgeo/grid3d/_grid_import.py
src/xtgeo/grid3d/_grid_import_xtgcpgeom.py
src/xtgeo/grid3d/_grid_wellzone.py
src/xtgeo/grid3d/_gridprop_import_eclrun.py
src/xtgeo/grid3d/_gridprop_roxapi.py
src/xtgeo/grid3d/_gridprops_io.py
src/xtgeo/grid3d/grid.py
src/xtgeo/grid3d/grid_properties.py
src/xtgeo/grid3d/grid_property.py
src/xtgeo/plot/baseplot.py
src/xtgeo/plot/grid3d_slice.py
src/xtgeo/plot/xsection.py
src/xtgeo/plot/xtmap.py

Refactor code quality

---

src/xtgeo/well/_well_oper.py
src/xtgeo/well/well1.py
tests/conftest.py
tests/test_etc/test_etc_make_avg_maps.py
tests/test_etc/test_etc_make_hcpv_maps.py
tests/test_plot/test_grid3dlayerplot.py
tests/test_plot/test_grid3dsliceplot.py
tests/test_plot/test_map.py
tests/test_plot/test_xsection.py
tests/test_surface/test_regular_surface.py
tests/test_surface/test_regular_surface_vs_cube.py
tests/test_well/test_well.py
tests/test_xyz/test_polygons_from_wells.py

Added a function to measure vertical distance between well and a surface #461 . 
Also some refactoring wrt pytest's conftest.py.

Well distance surface

---

docs/usage.rst

Fixed a small issue while looking through documentation

Fix syntax error example doc

---

.pre-commit-config.yaml
src/xtgeo/grid3d/_gridprop_op1.py
src/xtgeo/grid3d/_gridprop_roxapi.py

Adress #486 #487
(bandit check was also disabled on pre--commit, mysterious error)

Bugfix rms issues 2.14 simplefix

---

requirements/requirements.txt
requirements/requirements_setup_ci.txt
src/xtgeo/common/xtgeo_dialog.py
src/xtgeo/plot/xtmap.py
src/xtgeo/xyz/_xyz.py
tests/test_common/test_xtg.py

CLN: remove six as dependency

---

src/xtgeo/xyz/_xyz.py
src/xtgeo/xyz/points.py
src/xtgeo/xyz/polygons.py
tests/test_xyz/test_points_poly.py

Solves #505 
I've proposed a change for `dtname`, will need to be added for the others as well

FIX: Check validity on colnames when setting df

---

.gitignore
src/xtgeo/grid3d/_gridprop_import_roff.py
src/xtgeo/grid3d/_gridprop_roxapi.py
tests/test_roxarapi/test_roxarapi_reek.py

Fix gridprop bug roxapi

---

.github/workflows/ci-test-xtgeo.yml
src/xtgeo/common/calc.py

FIX: fix sphinx docstring warnings

---

tests/test_clib_errors.py

On some systems these tests were failing because it was possible
to open the file. This skips them if that is the case. There is
a risk that the tests will silently be skipped on different systems,
but they are testing a very rare occurence, so that risk should
be ok.

FIX: Skip test conditionally

---

.gitignore
docs/usage.rst
examples/grid3d_compute_stats.py
examples/grid3d_crop.py
examples/grid3d_get_df.py
examples/grid3d_print_init_csv.py
examples/grid3d_prop_as_map.py
examples/multiprocess_surfs.py
examples/regsurf_compute_stats.py
examples/run_examples.sh
examples/surf_threading.py
examples/surface_slice_cube.py
examples/surface_slice_grid3d.py
examples/wellpath_fence_sample.py

Update files in `examples/` and `docs/` to style
`s = xtgeo.surface_from_file("some") for all data types`

Update docs new init

---

tests/test_grid3d/test_grid.py

Reduce size of shoebox test

---

src/xtgeo/grid3d/_grdecl_format.py
src/xtgeo/grid3d/_grdecl_grid.py
src/xtgeo/grid3d/_grid_import_ecl.py
src/xtgeo/grid3d/_gridprop_import_grdecl.py
tests/test_grid3d/test_grdecl_format.py
tests/test_grid3d/test_grid_grdecl.py
tests/test_grid3d/test_grid_property_grdecl.py
tests/test_grid3d/test_grid_xtgformats_io.py

Refactors grdecl reading so that it fixes #581 #435 .

Refactor grdecl reading

---

docs/history.md
src/xtgeo/cube/cube1.py

Release 2.15.1

---

src/xtgeo/grid3d/grid_properties.py
tests/test_grid3d/test_grid_properties.py

BUG: Fix gridproperties iter

---

.github/workflows/ci-test-opm-integration.yml
pyproject.toml
requirements/pyproject.toml.komodo
requirements/requirements_dev.txt
requirements/requirements_dev_rms.txt
requirements/requirements_docs.txt
requirements/requirements_setup_ci.txt

Temporarily fixes https://github.com/equinor/xtgeo/issues/631

DOC: Fix sphinx version for sphinx-toolbox

---

src/xtgeo/grid3d/_grid_import_xtgcpgeom.py
tests/test_grid3d/test_grid_xtgformats_io.py

* Hdf5 import would incorrectly use row specifier for layer in partial read
* Hdf5 import would incorrectly use metadata for subgrid import
* Hdf5 and xtgformat would not set _xtgformat
* Hdf5 partial import would not correctly filter subgrids
* Hdf5 and xtgformat would look for scale and shift in _optional_, but
these are written to _required_.

BUG: Fix issues with xtgformat files

---

src/xtgeo/surface/regular_surface.py
tests/test_surface/test_regular_surface.py

**Issue**
Fix for issue #634. We want to keep `load_values()` but cannot let it depend on the deprecated function `from_file()`.
**Approach**
The approach is to re-read values from the file and explicitly set `values` on success. Raises `ValueException` if the object is not originating from a file.

Fix for issue 634

---

requirements/requirements.txt
src/xtgeo/grid3d/_gridprop_import_eclrun.py
tests/test_grid3d/test_grid_properties.py

BUG: Fix eclrun not handling dates as strings

---

tests/test_grid3d/test_grid.py
tests/test_grid3d/test_grid_operations.py
tests/test_grid3d/test_grid_properties.py
tests/test_grid3d/test_grid_property.py

This PR removes outdated/superfluous tests and increases test coverage by replacing log messages with asserts.

Clean ups in tests

---

.github/workflows/ci-test-doctest.yml
.github/workflows/codecov.yml
ci/jenkins/testkomodo.sh
conftest.py
pytest.ini
src/xtgeo/common/sys.py
src/xtgeo/cube/cube1.py
src/xtgeo/grid3d/_ecl_grid.py
src/xtgeo/grid3d/_grdecl_format.py
src/xtgeo/grid3d/_grid_etc1.py
src/xtgeo/grid3d/_gridprops_import_eclrun.py
src/xtgeo/grid3d/grid.py
src/xtgeo/grid3d/grid_properties.py
src/xtgeo/grid3d/grid_property.py
src/xtgeo/metadata/metadata.py
src/xtgeo/surface/regular_surface.py
src/xtgeo/well/blocked_well.py
src/xtgeo/well/blocked_wells.py
src/xtgeo/well/well1.py
src/xtgeo/well/wells.py
tests/test_grid3d/test_grid_dual_index.py

This PR makes sure the code examples given in the documentation work, and use them as test with doctest.

TST: Run examples with doctest

---

src/xtgeo/grid3d/_gridprops_import_eclrun.py
src/xtgeo/grid3d/grid_properties.py

Refactor gridproperties from file so that mutation of the object only happens locally in the class.

CLN: Refactor gridproperties from file

---

src/xtgeo/common/sys.py
src/xtgeo/well/_well_io.py
src/xtgeo/well/_well_roxapi.py
src/xtgeo/well/well1.py
src/xtgeo/well/wells.py
tests/test_well/test_deprecations.py
tests/test_well/test_well_hdf5.py

ENH: Deprecate initialization from file in Well

---

src/xtgeo/__init__.py
src/xtgeo/well/wells.py
tests/test_well/test_deprecations.py
tests/test_well/test_wells.py

ENH: Deprecate implicit initialization in wells

---

src/xtgeo/common/sys.py
src/xtgeo/cube/_cube_import.py
src/xtgeo/cube/cube1.py
tests/test_cube/test_cube.py
tests/test_cube/test_deprecations.py

ENH: Deprecated implicit initialization of Cube

---

src/xtgeo/__init__.py
src/xtgeo/well/blocked_wells.py
tests/test_well/test_blockedwells.py
tests/test_well/test_deprecations.py

closes #722 Note, depends on #721

ENH: Deprecate implicit init of BlockedWells

---

src/xtgeo/common/sys.py
src/xtgeo/grid3d/_grid_import.py
src/xtgeo/grid3d/_grid_import_roff.py
src/xtgeo/grid3d/grid.py
tests/test_grid3d/test_grid_bytesio.py

BUG: fix roff binary grid read/write byte streams

---

src/xtgeo/xyz/points.py
tests/test_xyz/test_points.py

BUG: Points.from_list was not working

---

src/xtgeo/xyz/_xyz_io.py

Convert to required type

---

src/xtgeo/grid3d/_grdecl_grid.py
tests/test_grid3d/test_grid_grdecl.py
tests/test_grid3d/test_grid_property_grdecl.py

Fix bug grdecl file formatting

---

.github/workflows/ci-test-xtgeo-cibuildwheel.yml
.github/workflows/test.yml

Confer #741 + request from ERT team

BLD: Add python 3.10 for tests and pypi

---

.github/workflows/ci-test-xtgeo-cibuildwheel.yml
src/clib/xtg/libxtg.h
src/xtgeo/common/calc.py
src/xtgeo/cube/_cube_import.py
src/xtgeo/cube/_cube_roxapi.py
src/xtgeo/roxutils/roxutils.py
tests/test_common/test_calc.py
tests/test_cube/test_cube.py

See issue #764 
Some visible refactoring in this PR, making routines smaller and hopefully better

Segy with missing traces, support for

---

src/xtgeo/grid3d/_ecl_inte_head.py
tests/test_grid3d/test_ecl_inte_head.py

BUG: E300 item IPHS in INTEHEAD is actually no. tracers

---

scripts/setup_utilities.py

The fix done in #815 does still fail on the `python setup.py clean` command. This PR here will re-introduce the `new_style` function from `scikit-build <= 0.15` locally, so it should work for `scikit-build >= 0.16`.
In addition unnecessary imports are removed, as well as a few coding technical issues reported by the linting tools.

BLD: further adjust setup_utilites

---

scripts/setup_utilities.py
src/xtgeo/grid3d/_gridprop_roxapi.py
src/xtgeo/grid3d/grid_property.py
tests/test_grid3d/test_grid_property.py
tests/test_grid3d/test_grid_property_etc.py

This solves issue reported in #816

Gridprop discrete codes issue

---

src/xtgeo/grid3d/_grdecl_format.py

BUG: Allow ECL kwords with spaces when checking

---

src/xtgeo/well/_well_roxapi.py
tests/test_roxarapi/test_roxarapi_reek.py

BUG: fix case where discrete well log is all undefined

---

.github/workflows/ci-test-xtgeo-cibuildwheel.yml

Resolve issue for MacOS when building and deploying CIBW

BLD: revert setup-python@v4 to v2

---

src/xtgeo/well/_blockedwell_roxapi.py
src/xtgeo/well/blocked_well.py

Solves #879  in a pragmatic way.
There is a need for a more throughout refactoring of the `Well1` and `BlockedWell`  classes, but that can be addressed later.

BUG: add realisation in blockedwell_from_roxar()

---

src/xtgeo/__init__.py
src/xtgeo/cube/cube1.py
src/xtgeo/grid3d/grid.py
src/xtgeo/plot/grid3d_slice.py
src/xtgeo/surface/_regsurf_cube_window.py
src/xtgeo/surface/_regsurf_cube_window_v3.py
src/xtgeo/surface/_regsurf_roxapi.py
src/xtgeo/surface/regular_surface.py
src/xtgeo/surface/surfaces.py
tests/test_surface/test_surface_cube_attrs.py

For `RegularSurface().slice_cube_window()`, the history is:
* Algorithm 1 was the first implementation, but with spagetti coding and slow performance
* Algorithm 2 is the second implementation with the C library, and tests shows at least a factor 10 in speed improvement
Due to hard-to-debug errors in the some corner cases with algorithm 2, a completely new routine is written in pure python now, and flagged as algorithm 3. In terms of speed it may be somewhat slower than algorithm 2, but in terms of code maintance and debugging it is much easier to control.
During the work some other small fixes and enhancements where made, which are separated in own commits.
Solves #887

Fix seismic slice cube issue maxneg etc

---

.github/actions/setup_xtgeo/action.yml
.github/workflows/ci-test-xtgeo-cibuildwheel.yml
pyproject.toml

Address first task in #928 
While working with this, repeated failures with tests GH actions on Windows triggered commit 7e06b262c9046f7fac211e2bd153a4a24c24b824

BLD: apply scikit-build-core < 0.6.0

---

SECURITY.md

DOC: Add SECURITY.md

---

.github/workflows/test.yml
conftest.py
pyproject.toml

TST: Use pytest-xdist

---

README.md
docs/readme.rst
docs/usage.rst
src/xtgeo/grid3d/grid.py
src/xtgeo/surface/regular_surface.py
src/xtgeo/well/well1.py
src/xtgeo/xyz/points.py

Adress #940 , except for `GridProperty()` class

Fix deprecated patterns docs

---

.github/workflows/mypy.yml
pyproject.toml

Resolves https://github.com/equinor/xtgeo/issues/890

Add mypy github action

---

conftest.py
tests/test_cube/test_cube.py
tests/test_grid3d/test_grid_ecl_grid.py
tests/test_grid3d/test_grid_egrid.py
tests/test_grid3d/test_grid_grdecl.py
tests/test_grid3d/test_grid_property.py
tests/test_grid3d/test_grid_property_grdecl.py
tests/test_grid3d/test_grid_xtgformats_io.py
tests/test_grid3d/test_gridprop_import_eclrun.py
tests/test_opm_integration/test_grid_io.py
tests/test_opm_integration/test_gridprop_io.py
tests/test_surface/test_file_io.py
tests/test_xyz/test_points.py

`deadline` must be removed from pytest-xdist in order not to fail randomly
closes #945

CLN: Remove deadline from tests

---

pyproject.toml

Pin numpy to lower than 2 version

---

src/xtgeo/grid3d/grid_property.py

FIX: Pass actual Roxar project to GridProperty

---

bin/xtgls.py
examples/grid3d_compute_stats.py
examples/grid3d_crop.py
examples/grid3d_print_init_csv.py
examples/grid3d_prop_as_map.py
examples/grid3d_properties_qc.py
examples/multiprocess_surfs.py
examples/regsurf_compute_stats.py
examples/surf_threading.py
examples/surface_slice_cube.py
examples/surface_slice_grid3d.py
examples/wellpath_fence_sample.py

Resolves #981
Executed `isort . && black .`

CLN: Run black and isort on codebase

---

src/xtgeo/common/calc.py

CLN: Add typing to common/calc

---

.github/workflows/test.yml

Enable OPM tests

---

src/xtgeo/common/calc.py
src/xtgeo/common/sys.py
src/xtgeo/cube/_cube_import.py
src/xtgeo/cube/cube1.py
src/xtgeo/grid3d/_ecl_logi_head.py
src/xtgeo/grid3d/_egrid.py
src/xtgeo/grid3d/_grdecl_grid.py
src/xtgeo/grid3d/_grid_etc1.py
src/xtgeo/grid3d/_gridprop_import_eclrun.py
src/xtgeo/grid3d/_gridprop_value_init.py
src/xtgeo/grid3d/_gridprops_import_eclrun.py
src/xtgeo/grid3d/_gridprops_import_roff.py
src/xtgeo/grid3d/_roff_grid.py
src/xtgeo/grid3d/_roff_parameter.py
src/xtgeo/grid3d/grid.py
src/xtgeo/grid3d/grid_property.py
src/xtgeo/surface/_regsurf_cube_window_v3.py
src/xtgeo/surface/_regsurf_oper.py
src/xtgeo/surface/surfaces.py
src/xtgeo/well/_well_aux.py
src/xtgeo/well/well1.py
src/xtgeo/well/wells.py
src/xtgeo/xyz/_xyz.py
src/xtgeo/xyz/_xyz_data.py
src/xtgeo/xyz/points.py
src/xtgeo/xyz/polygons.py

By scripting, the gist of it is:
```bash
find src/xtgeo -type f -name "*.py" -exec pyupgrade --py310-plus {} \;
git status | awk '{print $2}' | sort > log  (remove a few not needed files)
xargs -I {} sh -c 'isort --float-to-top --add-import "from __future__ import annotations" {}' < log
ruff check . --fix
isort . && black .
```
Resolves:  #994

CLN: Update code base to use py10 annotation

---

src/xtgeo/grid3d/_grid3d_utils.py
src/xtgeo/grid3d/grid_properties.py
tests/test_grid3d/test_grid_properties.py

CLN: Add types to GridProperties

---

ci/testkomodo.sh

CI: Run Komodo tests in the RMS environment

---

ci/testkomodo.sh

Forgot to link the `examples/` directory. Also felt it would be more correct to subshell the sourcing of roxenv to prevent potential conflicts and reduce the possible sources of errors.

CI: Fix Komodo ci script

---

src/xtgeo/grid3d/_ecl_logi_head.py

CLN: Add types to _ecl_logi_head

---

src/xtgeo/grid3d/_grid_refine.py

CLN: Add types to grid_refine

---

src/xtgeo/grid3d/_ecl_output_file.py

CLN: Add types to ecl_output_file

---

src/xtgeo/grid3d/grid_properties.py

DOC: Update deprecated GridProperties examples

---

.github/workflows/linting.yml
.github/workflows/mypy.yml
.github/workflows/test.yml

CI: Run CI nightly

---

mypy.ini
src/xtgeo/grid3d/_ecl_inte_head.py

CLN: Add types to ecl_inte_head

---

mypy.ini
src/xtgeo/grid3d/_roff_parameter.py

CLN: Add types to _roff_parameter

---

docs/contributing.rst

DOC: Update Tips section in docs/contributing.rst

---

.gitignore
pyproject.toml
src/xtgeo/__init__.py
src/xtgeo/cube/cube1.py
src/xtgeo/grid3d/grid.py
src/xtgeo/grid3d/grid_properties.py
src/xtgeo/grid3d/grid_property.py
src/xtgeo/surface/regular_surface.py
src/xtgeo/surface/surfaces.py
src/xtgeo/well/blocked_well.py
src/xtgeo/well/blocked_wells.py
src/xtgeo/well/well1.py
src/xtgeo/well/wells.py
src/xtgeo/xyz/points.py
src/xtgeo/xyz/polygons.py
tests/test_grid3d/test_grid3d_deprecations.py
tests/test_surface/test_deprecation.py
tests/test_surface/test_regular_surface.py
tests/test_well/test_well_deprecations.py
tests/test_xyz/test_xyz_deprecated.py

CLN: Move version file to version.py

---

mypy.ini
src/xtgeo/grid3d/_gridprop_roxapi.py
src/xtgeo/grid3d/grid_property.py

CLN: Add types to gridprop_roxapi

---

mypy.ini
src/xtgeo/grid3d/_gridprop_import_roff.py

CLN: Add types to gridprop-import-roff

---

bin/xtgls.py
src/xtgeo/cube/_cube_import.py
src/xtgeo/grid3d/_grid_etc1.py
src/xtgeo/grid3d/_grid_import_xtgcpgeom.py
src/xtgeo/grid3d/_grid_refine.py
src/xtgeo/grid3d/_grid_roxapi.py
src/xtgeo/grid3d/_gridprop_import_roff.py
src/xtgeo/grid3d/_gridprop_import_xtgcpprop.py
src/xtgeo/grid3d/_roff_grid.py
src/xtgeo/grid3d/grid.py
src/xtgeo/metadata/metadata.py
src/xtgeo/plot/xsection.py
src/xtgeo/surface/_regsurf_import.py
src/xtgeo/surface/regular_surface.py
src/xtgeo/well/_well_io.py
src/xtgeo/well/_wellmarkers.py
src/xtgeo/xyz/_xyz_io.py
src/xtgeo/xyz/points.py
tests/test_grid3d/test_grid.py
tests/test_grid3d/test_grid_operations.py
tests/test_grid3d/test_grid_roff.py
tests/test_grid3d/test_grid_xtgformats_io.py
tests/test_roxarapi/test_roxarapi_reek.py
tests/test_well/test_well_hdf5.py
tests/test_xyz/test_polygon.py

CLN: Replaced OrderedDict instances with dict (#1005)

---

.github/workflows/mypy.yml

CI: Run mypy on Python 3.8 as well

---

mypy.ini
src/xtgeo/grid3d/_gridprop_lowlevel.py

CLN: Add types gridprop-lowlevel

---

mypy.ini
src/xtgeo/grid3d/_grid_hybrid.py

CLN: Add types grid-hybrid

---

src/xtgeo/well/blocked_well.py

BUG: correct errors in code for BlockedWell

---

src/xtgeo/surface/_regsurf_oper.py
src/xtgeo/well/_blockedwell_roxapi.py
src/xtgeo/well/_blockedwells_roxapi.py
src/xtgeo/well/blocked_wells.py
src/xtgeo/well/well1.py
src/xtgeo/well/wells.py
src/xtgeo/xyz/_xyz_data.py
src/xtgeo/xyz/_xyz_oper.py
tests/test_plot/test_matplotlib_import.py
tests/test_roxarapi/test_roxarapi_reek.py

When running our Drogon workflow, the blocked wells workflow revealed that issues remained. This PR resolves these.
An important addition is adding tests for blocked well(s) towards Roxar API.
Some other issues were found e.g. relating to lazy loading of matplotlib. These are separated into own commits.
Closes #1053  (which was re-opened)

Further issues blockedwells

---

.github/workflows/test.yml
tests/test_plot/test_matplotlib_import.py

CI: Test against RMS-locked environments

---

mypy.ini
src/xtgeo/grid3d/_grid_wellzone.py

CLN: add types to grid_wellzone

---

src/xtgeo/common/constants.py
src/xtgeo/cube/cube1.py
src/xtgeo/well/_blockedwell_roxapi.py
src/xtgeo/xyz/_xyz_data.py
tests/test_roxarapi/test_roxarapi_reek.py
tests/test_well/test_well_xyzdata_class.py

Hopefully last round to solve issue with blocked wells #1053.
Needed to revert some "nitty-gritty" behavior in order to make this backward compatible with previous xtgeo versions

BUG: address remaining issues with refactoring XYZ data wrt blocked wells

---

.github/workflows/test.yml
src/xtgeo/surface/regular_surface.py
src/xtgeo/well/wells.py
src/xtgeo/xyz/polygons.py
tests/test_surface/test_regular_surface.py

Was surprised this was not caught by tests and also found out why.

BUG: Lazily import xtgeo.plot in quickplots

---

mypy.ini
src/xtgeo/common/calc.py
src/xtgeo/grid3d/_grid_etc1.py
src/xtgeo/grid3d/grid.py
src/xtgeo/grid3d/grid_properties.py
src/xtgeo/grid3d/grid_property.py
src/xtgeo/grid3d/types.py

CLN: add types to grid_etc1

---

docs/index.rst
docs/xtgeo_4_migration.md
src/xtgeo/surface/regular_surface.py

Adds to #1059
This guide is incomplete, but checking in for feedback before writing more

DOC: Add xtgeo 4.0 migration guide

---

pyproject.toml
src/xtgeo/__init__.py
src/xtgeo/grid3d/_roff_grid.py
src/xtgeo/surface/regular_surface.py
src/xtgeo/well/wells.py
src/xtgeo/xyz/polygons.py
tests/test_plot/test_matplotlib_import.py

CLN: Use xtgeoviz for quickplots

---

.github/workflows/linting.yml

CI: Run ruff format check in linting

---

docs/xtgeo_4_migration.md
src/xtgeo/grid3d/grid_properties.py

Add to xtgeo 4 migration guide

---

mypy.ini
src/xtgeo/grid3d/_gridprop_import_eclrun.py
src/xtgeo/grid3d/_gridprop_import_grdecl.py

CLN: add typing to gridprop imports

---

mypy.ini
src/xtgeo/grid3d/_grid_export.py

CLN: Add typing to `_grid_export`

---

mypy.ini
src/xtgeo/grid3d/_grid_import.py
src/xtgeo/grid3d/_grid_import_ecl.py

CLN: add typing to _grid_import_ecl

---

src/xtgeo/xyz/_xyz_roxapi.py
tests/test_roxarapi/test_roxarapi_reek.py

Fix bug caused by #1117, and add tests to avoid issue in future.

FIX: Regression fix on #1117

---

src/xtgeo/xyz/_xyz_roxapi.py

Yet another regression fix on #1117, this PR reverts back to masking undefined attribute values on roxar points instead of using nan values. 
Was a bit tricky to detect, RMS accepts nan values when setting and getting roxar point attributes. However if an attribute contained any nan values an error occurred in the horizon modelling job, saying there were no data inside the model boundary for the specific horizon.

FIX: Set undefined point attributes to masked instead of nan

---

.github/workflows/linting.yml
.github/workflows/test.yml
CMakeLists.txt
pyproject.toml
src/lib/CMakeLists.txt

CI: Lint with clang-format and cmake-format

---

src/xtgeo/cube/cube1.py
tests/test_cube/test_cube.py

This also contains more checks on `values` input, e.g. if dimensions are correct.
Solves #1166

BUG: accept masked arrays as values to Cube()

---

src/xtgeo/grid3d/_gridprop_export.py

Fix a typo in code
Closes #1172

BUG: fix typo in roffio.Format.ASCII statement

---

src/xtgeo/xyz/_xyz_roxapi.py
tests/test_roxarapi/test_roxarapi_reek.py

PR with bugfix to allow having other xyz column names than the xtgeo defaults for points and polygons. 
Also added a check that the xyz name attributes are present in the dataframe before trying to do the export in case users only updates the dataframe columns and forget to update the corresponding xyz name attributes.

FIX: Allow non-default XYZ names on roxar export for xyz

---

tests/test_grid3d/test_grid_property.py

TST: Add roff_ascii export regression test

---

src/xtgeo/surface/_regsurf_cube_window_v3.py
src/xtgeo/xyz/_xyz_oper.py
tests/test_surface/test_surface_cube_attrs.py
tests/test_xyz/test_polygon.py

DEP: Replace deprecated scipy interp1d in two modules

---

.github/workflows/publish.yml
pyproject.toml

Unpin pytables version for Python 3.8

---

.github/actions/setup_xtgeo/action.yml
.github/workflows/build_docs.yml
.github/workflows/publish.yml
.github/workflows/test.yml

Update actions to latest version

---

src/xtgeo/grid3d/grid.py

Fix types of increment in function call

---

src/xtgeo/grid3d/grid_properties.py
tests/test_grid3d/test_grid3d_deprecations.py

Fix parameter name in GridProperties().from_file()

---

src/xtgeo/cube/cube1.py
src/xtgeo/surface/regular_surface.py
tests/test_cube/test_cube.py
tests/test_surface/test_regular_surface.py

BUG: Fix two bugs, one for Cube and one for RegularSurface 

---

.github/workflows/publish.yml
.github/workflows/test.yml

Resolves #1193
Resolves #1199 
Resolves #1208

CI: Re-enable macOS builds

---

src/xtgeo/grid3d/_grid_wellzone.py
src/xtgeo/grid3d/_gridprop_import_roff.py
src/xtgeo/grid3d/grid.py
src/xtgeo/grid3d/grid_property.py
tests/test_etc/test_etc_make_avg_maps.py
tests/test_etc/test_etc_make_hcpv_maps.py
tests/test_grid3d/test_grid.py
tests/test_grid3d/test_grid3d_deprecations.py
tests/test_grid3d/test_grid_operations.py
tests/test_grid3d/test_grid_property.py
tests/test_grid3d/test_grid_property_roff.py
tests/test_grid3d/test_grid_vs_poly.py
tests/test_opm_integration/test_grid_io.py

Doesn't include GridProperties, which will follow in a stacked PR.
Adds to #1088

DEP: Complete xtgeo 4 grid/gridprop deprecations

---

.github/workflows/test.yml

CI: ensure that tests work on Windows latest and Python 3.12 (TCL issue)

---

src/lib/CMakeLists.txt
src/lib/include/xtgeo/cube.hpp
src/lib/src/cube/cube.cpp
src/lib/src/init.cpp
src/xtgeo/common/log.py
src/xtgeo/cube/_cube_window_attributes.py
src/xtgeo/cube/cube1.py
src/xtgeo/surface/regular_surface.py
tests/test_surface/test_surface_cube_attrs.py

This PR replaces #1234
It should close issue #1232
After a lot of testing, I found that doing numpy statististics where rather ineffecient, and made a C++ (pybind11) routine to do that task. That speed up the task a magnitude of order, and a typical execution (total) could go from 40 seconds to 5 seconds.

ENH: improve cube window attributes

---

src/xtgeo/cube/cube1.py

Fix imprecise documentation after PR #1238, completing issue #1232

DOC: fixup of documentation for Cube.compute_attributes_in_window()

---

src/xtgeo/well/blocked_wells.py
src/xtgeo/well/well1.py
src/xtgeo/xyz/_xyz_io.py

CLN: fix ruff linting failure

---

src/xtgeo/grid3d/_gridprop_export.py
src/xtgeo/grid3d/grid.py
src/xtgeo/io/_file.py
src/xtgeo/surface/regular_surface.py

BUG: fix check_folder to not raise exception for mem. streams

---

src/xtgeo/xyz/_xyz_roxapi.py
tests/test_roxarapi/test_roxarapi_reek.py

BUG, TST: smaller fixes wrt Roxar API

---

ci/testrmsenv.sh
src/xtgeo/grid3d/_grid_etc1.py
src/xtgeo/grid3d/_gridprop_lowlevel.py
src/xtgeo/grid3d/grid.py
src/xtgeo/surface/regular_surface.py
src/xtgeo/xyz/_xyz_io.py
src/xtgeo/xyz/points.py
tests/test_grid3d/test_ecl_inte_head.py
tests/test_grid3d/test_grdecl_format.py
tests/test_opm_integration/test_gridprop_io.py

Resolves part of https://github.com/equinor/rms-sys/issues/267
Added a bash script that can be run from the github workflows to execute the xtgeo unit tests towards an RMS Python Environment. 
The script copies the required test files, installs the test dependencies and and runs the pytests.

CI: Add script for running tests from github worklow

---

src/xtgeo/grid3d/grid.py

CLN: correct typing for gfile in Grid grid_from_file

---

src/xtgeo/xyz/_xyz.py
src/xtgeo/xyz/_xyz_oper.py
src/xtgeo/xyz/polygons.py
tests/test_xyz/test_polygon.py

Also do similar fixes for special columns tname, dtname, hname, dhname
Closes #1310

BUG: fix renaming of 'pname' in Polygons

---

src/xtgeo/surface/_regsurf_export.py
tests/test_surface/test_regular_surface.py

BUG: fix Irap ascii export bug that may occur in some cases

---

pyproject.toml
src/xtgeo/io/_file.py
src/xtgeo/xyz/_xyz_io.py
src/xtgeo/xyz/points.py
src/xtgeo/xyz/polygons.py
tests/test_surface/test_regular_surface_vs_points.py
tests/test_xyz/test_points.py
tests/test_xyz/test_polygon.py

ENH: add support for csv and parquet i/o for Points/Polygons

---

src/xtgeo/grid3d/_grid_etc1.py
src/xtgeo/well/blocked_well.py
src/xtgeo/well/blocked_wells.py
src/xtgeo/well/well1.py

CLN: Switch from *args, **kwargs to keyword in well.from_roxar and well.to_roxar method

---

src/xtgeo/grid3d/grid.py

DOC: Fix typo

---

src/xtgeo/metadata/metadata.py

TYP: add types for _OptionalMetadata

---

examples/surface_slice_cube.py
src/xtgeo/cube/_cube_window_attributes.py
tests/test_surface/test_surface_cube_attrs.py

Closes #1372  (bug)
Closes #1373  (documentation)

BUG,DOC: fix a bug in cube.compute_attributes_in_window in case where input cube has dead traces.

---

src/xtgeo/grid3d/_gridprop_op1.py
src/xtgeo/grid3d/_gridprop_roxapi.py
src/xtgeo/grid3d/grid_property.py
tests/test_roxarapi/test_roxarapi_reek.py

Various issues relaetd to discrete vs constinuous grid property objects

BUG: fix various issues related to discrete grid properties

---

src/xtgeo/grid3d/_gridprop_roxapi.py
tests/test_roxarapi/test_roxarapi_reek.py

BUG: resolve an error when setting icon in RMS with varying data type

---

src/xtgeo/grid3d/grid.py
tests/test_grid3d/test_grid.py

ENH: Implement get_zoneprop_from_subgrids method

---

mypy.ini
src/xtgeo/io/_file.py
src/xtgeo/metadata/metadata.py

Resolve #1365 
Added type annotations to xtgeo.metadata.py file. 
Deleted duplicate method _optional in metadata.py file. @jcrivenaes , can you please check if that's alright ?

TYP: Type annotations for metadata.py
