equinor/xtgeo

src/xtgeo/surface/surfaces.py
tests/test_surface/test_surfaces.py

Relates to #170 
Relates to https://github.com/equinor/webviz-subsurface/issues/69
This PR adds an `apply` function to the surface collection class to calculate statistics.
The function must return a numpy array with the same shape as the input surface.
Example:
```python
so = xtgeo.surface.surfaces.Surfaces([list of surfaces])
res = so.apply(np.nanstd, axis=0, ddof=1)
print(res)
res = so.apply(np.nanmin, axis=0)
print(res)
res = so.apply(np.nanmax, axis=0)
print(res)
res = so.apply(np.nanmean, axis=0)
print(res)
```

WIP: Generic apply function for the Surfaces collection class

---

src/xtgeo/cube/cube1.py
src/xtgeo/well/well1.py
src/xtgeo/xyz/_xyz.py

`Cube`, `Well` and `xyz`  `from_file()` does not report the name of the file if the file is missing.
For larger scripts it can be hard to figure out which file is the culprit.
Duplicated the code from `RegularSurface.from_file` into these classes.

Include filename in error message if file does not exist

---

src/xtgeo/common/constants.py
src/xtgeo/grid3d/_grid_etc1.py
src/xtgeo/plot/xtmap.py
src/xtgeo/surface/_regsurf_cube.py
src/xtgeo/surface/_regsurf_export.py
src/xtgeo/surface/_regsurf_gridding.py
src/xtgeo/surface/_regsurf_import.py

I.e. not any longer by _ctgeo.UNDEF etc. This reason for this is that some build did not transfer
the define CONSTANT with consistent names; a SWIG issue I think

Changes CONSTANT system so only defined by xtgeo for Python

---

src/xtgeo/plot/xsection.py

Change log plotting to use lineCollection.
Added idx and cmap options for zonelog.
Added option to not plot log legends. 
Added option to specify log width.
Old log plotting:
Update plots log as single line with colored segments. Results in less gaps in the log:

Change xsections log plotting

---

src/xtgeo/clib/xtg/grd3d_make_z_consistent.c
src/xtgeo/grid3d/_gridprop_etc.py
src/xtgeo/grid3d/grid.py
src/xtgeo/grid3d/grid_properties.py
src/xtgeo/grid3d/grid_property.py
src/xtgeo/well/_well_oper.py
tests/test_common/test_xtg.py

This is done to restore a feature in version 2.0, cf. #325. Circular references could then be present again which could trigger memory leakage, so need to look at `weakref` possible to improve further.

Gridprop linkgrid issue3

---

src/xtgeo/grid3d/_grid3d_fence.py
src/xtgeo/grid3d/_gridprop_lowlevel.py

This allows me to run plot_grid3d() with discrete parameters, but it looks like there are some interpolation artifacts? Maybe better to fix `grd3d_get_randomline()` to work with int array?

Fix grd3d_get_randomline() for discrete parameters

---

src/xtgeo/plot/xsection.py

Interpolation parameter added for plot_grid3d(). Interpolation will be set to 'nearest' if grid param is discrete.
Fixes https://github.com/equinor/xtgeo/issues/399

xsection: Interpolation for plot_grid3d()

---

HISTORY.md
src/xtgeo/grid3d/_grid_wellzone.py
src/xtgeo/grid3d/grid.py

Fixed a compatibility issue with pandas version < 0.23 (as RMS uses 0.21.0). Added two new keys to report_zonemismatch function

Fix issues for report gridmatch

---

src/xtgeo/surface/_regsurf_cube_window_v2.py
tests/test_surface/test_regular_surface_vs_cube.py
tests/test_surface/test_surface_cube_attrs.py

If `attribute` is given in list context, a dict shall be returned even if there is just one attribute, #426

Fix an issue wrt #426

---

ci/jenkins/testkomodo.sh
tests/test_common/test_system.py

Add testKomodo.sh used for the komodo test framework to run tests after building a new komodo release.

Add testKomodo.sh file

---

tests/test_common/test_system.py

Using "setup.py" in a unit test generated errors in Komodo bleeding; replacing with a file in test repo.

FIX: repair test, shall work without xtgeo repo files.

---

tests/conftest.py
tests/test_grid3d/test_grid_dualporo.py

Adresses #478 
In order to more easily set the path to location of xtgeo-testdata, a fixture containing the path, set by the environment/cli-options is added. Currently, some tests assume the location is `../xtgeo-testdata` and some use the environment variable `XTG_TESTPATH`. The idea is to move all useage of xtgeo-testdata to get the path through fixtures.

Add testdatapath to pytest options

---

tests/test_common/test_system.py

Refactor of `test_system.py` to use testdata fixture. Uses parametrization to use more testdata, but executes the same tests.
This continues the work started in https://github.com/equinor/xtgeo/pull/479

TST: Refactor test_system to use testdata fixture

---

tests/test_grid3d/test_grid_dual_index.py

The roxar api implements dual index systems, but xtgeo does not currently support them. This adds a failing test that describes the desired behavior. The feature request is described in https://github.com/equinor/xtgeo/issues/491 and https://github.com/equinor/xtgeo/issues/306 .

TST: Add failing test for dual index systems

---

.github/workflows/ci-test-xtgeo-cibuildwheel.yml
.github/workflows/ci-test-xtgeo-merge.yml
.github/workflows/ci-test-xtgeo.yml
.github/workflows/codecov.yml
.github/workflows/deploy-xtgeo-pypi.yml
docs/history.md
pyproject.toml
pytest.ini
requirements/requirements.txt
requirements/requirements_dev.txt
requirements/requirements_dev_rms.txt
setup.py
tests/test_common/test_system.py
tests/test_surface/test_regular_surface.py

Refers to issue #530. Python 3.9 support for PYPI is limited to Linux only, as the dependency pytables seems to miss wheels for Windows and MacOS for this python version. 
EDIT(1): pytables is not a build dependency, still I have trouble with running a multibuild install for Python 3.9 for MacOS and Windows
EDIT(2): The pytables package is currently not important (just for some code that has a "experimental" flag, i,.e wells export to HDF5 via pandas) so a fix is to make pypi for all platforms, and limit the tests for MacOS and Win until pytables is ready for Python 3.9 in PYPI. See also issue #539.

Support for python 3.9 in PYPI

---

src/clib/xtg/grd3d_scan_roffbinary.c

This is a quite small commit, awaiting a rewrite of the ROFF scan (#536), but it fix an urgent issue. It solves reading very large ROFF files described in #537.

BUG: change datatype for counters, related to #537

---

src/clib/xtg/grd3d_translate.c

In `grd3d_translate` the loop goes beyond the bound of zcorn. The function should probably use the given size of the vector anyways.

BUG: fix bound for zcorn in grd3d_translate

---

tests/test_grid3d/grid_generator.py

The test data generated before made the test flaky on some hardware
setups

FIX: Reduce size of generated test grid for limit

---

requirements/requirements.txt
src/clib/xtg/surf_export_irap_ascii.c
src/xtgeo/__init__.py
src/xtgeo/common/sys.py
src/xtgeo/surface/_regsurf_export.py
src/xtgeo/surface/_regsurf_grid3d.py
src/xtgeo/surface/_regsurf_import.py
src/xtgeo/surface/_regsurf_roxapi.py
src/xtgeo/surface/regular_surface.py
tests/test_surface/conftest.py
tests/test_surface/test_deprecation.py
tests/test_surface/test_file_io.py
tests/test_surface/test_new_surface.py
tests/test_surface/test_regular_surface.py
tests/test_surface/test_surfaces.py

This shows an extended example of how we could handle the initialization in a more consistent matter. A couple of notes:
1. ~~In a real implementation we would swap the place of these two classes to avoid breaking the API~~ Now it is an example of a real implementation
2. ~~This is meant as an example, and is not complete (would add all the import functions to `data_import_factory`)~~
3. The reasoning behind this pattern of coding is that explicit is better than implicit
4. This has a side effect of making it much easier to test the class, as there is only one way to initialize, meaning we can test that in isolation, and not for each possible file type.
5. We can also easily test the import functions, as they are only meant to read a file and return some values
6. ~~Using a second, dummy …

API: change initialization for RegularSurface

---

.github/workflows/ci-test-xtgeo-cibuildwheel.yml
.github/workflows/ci-test-xtgeo.yml
.github/workflows/deploy-xtgeo-pypi.yml

Github actions included swig in setup:
https://github.com/actions/virtual-environments/issues/3342
Solves: #569

BLD: remove swig install - comes preinstalled

---

src/clib/xtg/x_ijk2ib.c

It is perhaps a bit drastic to log an error if we go outside the grid. I have changed it to warning here, but maybe it should be removed altogether?

FIX: change error to warning

---

src/clib/xtg/grd3d_conv_grid_roxapi.c
tests/test_roxarapi/test_roxarapi_reek.py

When testing inside roxar environment, some tests failed. It was found to be caused by this construct in `grd3d_conv_grid_roxapi.c`:
```
ib0 = x_ijk2ib(i - 1, j - 1, k, ncol, nrow, nlay + 1, 0);
ib1 = x_ijk2ib(i, j - 1, k, ncol, nrow, nlay + 1, 0);
ib2 = x_ijk2ib(i - 1, j, k, ncol, nrow, nlay + 1, 0);
ib3 = x_ijk2ib(i, j, k, ncol, nrow, nlay + 1, 0);
if (ib0 < 0 || ib1 < 0 || ib2 < 0 || ib3 < 0) {
memset(zcorners, 0, sizeof(double) * nzcorners);
throw_exception("Loop through grid resulted in index outside "
"boundary in grd3d_conv_grid_roxapi");
return EXIT_FAILURE;
}
```
This appears OK, but further below in the code, only selected of values of ib are applied if in corners or on edge on grid. Hence negative values will not be applied anyway,
Thus, the code is refactored a bit.

BUG: fix checks on indices in set_grid in roxar api

---

requirements/requirements_test.txt
tests/test_common/test_system.py
tests/test_cube/test_cube_xtgformats_io.py
tests/test_grid3d/test_grid_property_roff.py
tests/test_grid3d/test_grid_xtgformats_io.py
tests/test_surface/test_regular_surface_xtgformats_io.py

Several tests were used to benchmark reading/writing. Unfortunately that setup would use a lot of disk space which ends up being problematic on some Jenkins.
The tests were changed to use pytest-benchmark.
Refactoring the benchmarks reduced the test coverage of `_XTGeoFile` so additional unit-tests were added.
roff grid parameters coverage seems dependent on data generation so additional unit tests were added.

TST: Reduce disk usage of export/import benchmarks

---

.github/workflows/ci-test-xtgeo-cibuildwheel.yml
.github/workflows/ci-test-xtgeo-merge.yml
.github/workflows/codecov.yml
.github/workflows/deploy-xtgeo-pypi.yml
tests/test_surface/test_file_io.py

Default deadlines have changed and are now sufficient for these tests.

TST: Use default deadline for surface io tests

---

src/xtgeo/cube/_cube_export.py

Docstring had additional argument engine which was not present in function signature.
closes #612

DOC: Fix docstring of _export_segy_segyio

---

src/xtgeo/common/sys.py
tests/test_common/test_system.py

The XTGeoFile.detect_fformat would crash for several variations of memstream and short files. Fixed this by being more careful with accessing members.

BUG: Fix XTGeoFile detect_fformat

---

tests/conftest.py

Our CI timings might be unreliable so sometimes hypothesis will report a slow test while the problem is a hiccup on the CI side.

TST: Suppress ci hypothesis healthcheck too_slow

---

requirements/requirements.txt
src/xtgeo/surface/_surfs_import.py
src/xtgeo/surface/surfaces.py

~~This PR is meant as a discussion topic. In several classes the construction of the objects are a bit complicated to read, and generally take in `*args` and `**kwargs`, there is nothing inherently wrong with that, but because they can be constructed in so many different ways I find it a bit hard to follow the code flow. I would propose we change to the pattern I have suggested in this PR, in that we make the constructor explicit, and provide `@classmethods` for the different initialization options instead, as that is more standard python. This is a breaking change, but I think it would be an improvement in the long run, and make it easier to extend the functionality.~~
~~To avoid having to bump the major version immediately it is possible to deprecate the old behavior by rewriting the …

Make Surfaces init more explicit

---

.pre-commit-config.yaml
codecov.yml
src/clib/xtg/cube_import_segy.c
src/clib/xtg/cube_scan_segy_hdr.c
src/xtgeo/cube/_cube_import.py
src/xtgeo/cube/cube1.py
tests/test_cube/snapshots/test_cube/test_segy_cube_scan/reek_cube_scan_header.txt
tests/test_cube/snapshots/test_cube/test_segy_cube_scan/reek_cube_scan_traces.txt
tests/test_cube/test_cube.py

Adresses #606 
Importing cube with engine='xtgeo' would previously use the xtgeo implementation to import a cube. However, this was deprecated. However, instead of raising an exception, importing with engine != 'segyio' would result in the default cube.
Changed behavior to raising an exception, and cleaned up the old import code which is still used in scanning.

BUG: Fix deprecated segy with engine='xtgeo'

---

src/xtgeo/grid3d/_ecl_grid.py
tests/test_grid3d/test_grid_ecl_grid.py

Before warning would be given if any of map axis and map units were missing, and a conversion was required. However, we only need to warn if map axes are given but no units.

BUG: Less warnings about missing mapaxes and unit

---

src/xtgeo/grid3d/_egrid.py
src/xtgeo/grid3d/_grdecl_grid.py
src/xtgeo/grid3d/_roff_grid.py

Function is unnecessary as np.array_equal(None, None) is True. Closes #699

CLN: Remove maybe_array_equal

---

src/xtgeo/grid3d/_ecl_grid.py
src/xtgeo/grid3d/_egrid.py
tests/test_grid3d/egrid_generator.py
tests/test_grid3d/test_grid_ecl_grid.py
tests/test_grid3d/test_grid_egrid.py

Fixes #727 
The assumption before was that at most one NNCHEADA would follow a NNCHEAD keyword in a EGRID file.
This assumption was incorrect. The code has changed so that the number of NNCHEAD is independent from the number of NNCHEADA and they might come interspersed in any order.
It seems that libraries and simulators implementing LGR's output these sections with NNCHEAD before NNCHEADA, ordered in some way by LGR index. The current implementation is oblivious to this detail, but does preserve the order of these sections.

Fix egrid nnc amalgamation

---

src/xtgeo/grid3d/_egrid.py
tests/test_grid3d/egrid_generator.py
tests/test_grid3d/test_grid_egrid.py

Backports ca780b877dfb451ee9988659fc85deb83698eba6 to 2.15postfix . This reuses the misspelled variable name indecies as that cleanup is not (and perhaps should not be) backported. The RMS will also fail as we have not backported that CI change.

Backport NNC fix to 2.15postfix

---

src/xtgeo/surface/regular_surface.py
tests/test_surface/test_regular_surface.py

surface_from_file would throw a segfault when file is missing, fixed with a check on the python side.

BUG: handle not found file in surface_from_file

---

src/xtgeo/xyz/points.py
src/xtgeo/xyz/polygons.py
tests/test_grid3d/test_deprecations.py

Minor issues:
* Tests runs (pytest) now give 3 temporary "grid.*" files at the top folder; move these to tmp path
* _reset() methods in Polygons and Points overrrides super _reset(); so rename
* redefine a few fixture names so avoid "outer scope" linting warnings
* Minor reorder of import statements in top of files (automatic from isort/black)

Minor code cleaning

---

tests/test_surface/test_file_io.py
tests/test_surface/test_new_surface.py

pytest.approx no longer wants to work with unordered sequences

TST: Solve compatibility with pytest 7.1

---

.github/actions/build-xtgeo/action.yml
.github/workflows/test.yml
src/clib/cxtgeo.i
src/clib/xtg/grd3d_ecl_tsteps.c
src/clib/xtg/grd3d_scan_eclbinary.c
src/clib/xtg/grd3d_scan_roffbinary.c
src/clib/xtg/libxtg.h
src/xtgeo/common/constants.py
src/xtgeo/grid3d/_grid3d_utils.py
src/xtgeo/grid3d/_gridprops_import_eclrun.py
src/xtgeo/grid3d/grid_properties.py

This relates to issue #767  and two issues have been identified and solved:
* Maximum number of keywords need an increase and is now 1 million (was 100 k)
* In case of LGR's the scanning for dates went wrong; this is now fixed
In addition, MAXKEYWORDS and MAXDATES are now centralized, and some other internal fixes (SWIG technical) was done

Fix issue #767  scanning ECL binary files

---

src/clib/CMakeLists.txt

CMP0074 NEW allows new ways of specifying search paths for
find_program. SWIG_ROOT will be required to to build xtgeo in case
HOSTNAME is empty, but there is no newer SWIG on standard paths.
Testing this on equinor machines can be achieved by executing
```bash
HOSTNAME= pip install . # Fails: Could NOT find SWIG: Found unsuitable version "2.0.10"
SWIG_ROOT=/prog/res/opt/rhel7/swig_4.0.2 HOSTNAME= pip install . # Works
```

BLD: Enable CMP0074 NEW to allow SWIG_ROOT

---

src/clib/xtg/surf_import_ijxyz_tmpl.c
src/xtgeo/surface/_regsurf_import.py

The C function surf_import_ijxyz_tmpl may return -1 which means that using a template fails. Earlier this was not handled; now a ValueError is raised in the receiving python code. Context: Auto4D bug report.
This Exception is then used in the auto4D code to make a workaround.

BUG: ensure raising a ValueError if return -1

---

src/xtgeo/grid3d/_grid_roxapi.py
src/xtgeo/surface/_regsurf_roxapi.py
src/xtgeo/surface/regular_surface.py
src/xtgeo/xyz/_xyz_io.py
src/xtgeo/xyz/_xyz_roxapi.py
src/xtgeo/xyz/points.py
src/xtgeo/xyz/polygons.py
tests/test_roxarapi/test_roxarapi_reek.py
tests/test_xyz/test_points.py

This PR has several commits targeted to Roxar API:
* General improvements/refactor in RMS integration tests
* Add support for "General 2D" in RMS GUI tree (Roxar API >= 1.6) for both `RegularSurface()` and `_XYZ()` based classes
* Add support for Trend Surfaces in RMS GUI
* Add support for writing subzones/subgrids for Roxar API >= 1.6
* From Roxar API 1.6, setting and getting point attributes via the API is possible and now implemented. Earlier a workaround using tmp files and `save()` + `load() `have been implemented, which should still work for Roxar  API < 1.6. Polygons support is postponed.

Roxar api add new features

---

src/xtgeo/surface/regular_surface.py

Supported file format for creating regsurf from file has not been updated for a while. This adds all supported format to docs based on https://github.com/equinor/xtgeo/blob/629c61b5c680d6ed66c3a270231bb1d589bcfdf5/src/xtgeo/surface/regular_surface.py#L184

add new supported file format for regsurf for docs

---

src/clib/xtg/grdcp3d_get_vtk_esg_geometry_data.c
src/clib/xtg/libxtg.h
src/xtgeo/grid3d/_grid_etc1.py
src/xtgeo/grid3d/grid.py
tests/test_grid3d/test_grid.py

Get geometry data consisting of vertices and cell connectivities suitable for use with VTK's explicit structured grid (ESG) class, `vtkExplicitStructuredGrid`.
Functionality is exposed through  `Grid.get_vtk_esg_geometry_data()` which returns theESG  geometry data in two separate arrays:
* One vertex array containing the grid's vertex coordinates
* One separate array with explicit connectivities for the hex elements
Also tries to remove duplicate nodes, but this is WIP
Todos:
* Do we still need Grid.get_vtk_geometries() that was added in PR #770 ?

Get grid geometry in format suitable for use with VTK's `vtkExplicitStructuredGrid`

---

src/xtgeo/surface/regular_surface.py
tests/test_surface/test_regular_surface.py

When regular surfaces are imported via `_import_irap_binary_purepy()` their string representations show as masked in their entirety despite having unmasked values. As discovered in (#677) this can cause hash collisions. It's not clear to me why numpy represents arrays like this in this particular case.
The solution in this PR is to ignore the mask and concatenate the non-masked bytes-as-hex to the hashed string. Simply converting the non-masked array to a string was significantly slower, hence the tobytes-hex. This avoids the problematic behavior while staying accurate to the underlying data in the file.
Some simple tests are included. They require the files referenced in the original issue to be added to xtgeo-testdata.

Resolve `generate_hash()` collisions in regular surfaces (#677)

---

src/clib/xtg/grd3d_ecl_tsteps.c
src/clib/xtg/grd3d_scan_eclbinary.c
src/xtgeo/grid3d/grid_properties.py
tests/test_grid3d/test_grid_properties.py

As noted in (#714), when given a non-existent file, `scan_dates()` and `scan_keywords()` segfault. The segfault is a result of calling `rewind()` on the `NULL` `FILE *` pointer passed to the C-layer functions.
This PR resolves the problem at both the Python and C side by checking the existence of the file in Python, but still failing more gracefully in C as a fail-back if a `NULL` pointer somehow makes it there besides. A more robust solution to this genera of problem might be a reasonably placed call to `check_file()` on the instantiation of an `_XTGeoFile` object.
Simple tests included.

Fail gracefully when GridProperties `scan_dates()`/`scan_keywords()` are given a non-existent file

---

src/xtgeo/grid3d/_find_gridprop_in_eclrun.py
tests/test_grid3d/test_grid_property.py

This PR is to address issue #753 where EGRID file reported 23 active cells from total 24 cells. But in the INIT file, the properties are reported for either 24 cells or 22 active cells.
The approach that have been done in ResInsight is to override ACTNUM when PORV is found in INIT file.
https://github.com/OPM/ResInsight/blob/6d5e303361a1aa91d0ad01ab3987e2abaaf8dab6/ApplicationLibCode/FileInterface/RifActiveCellsReader.cpp#L55-L114

ENH: Update ACTNUM based on value of PORV in INIT file

---

.github/workflows/ci-test-xtgeo-cibuildwheel.yml
.github/workflows/test.yml
src/xtgeo/grid3d/_ecl_grid.py

This is triggered by cases where OPM-Flow seems to output EGRID with splits in inactive cells.

FIX: change error to warning for ZCORN splits/overlaps

---

src/xtgeo/grid3d/_grid3d_utils.py
tests/test_grid3d/test_grid_properties.py

This is about eclipse keywords in INIT and UNRST files that may contain spaces, while scanning keys. One known case is usage of tracers in E100 that may provide names like "W8 F".
Solves #834

BUG: handling of ECL keywords with spaces in scanning

---

src/xtgeo/grid3d/_gridprops_import_roff.py
src/xtgeo/grid3d/grid_properties.py
tests/test_grid3d/test_grid_properties.py

This fix both the `names="all"` issue as well as it checks for valid keywords.
Solves #836

BUG: reading ROFF multiple gridproperties, "all"

---

src/xtgeo/grid3d/_ecl_inte_head.py
src/xtgeo/grid3d/_find_gridprop_in_eclrun.py
tests/test_grid3d/test_ecl_simpleb8_cases.py
tests/test_grid3d/test_grid_property.py

This is a follow up of closed PR #807, and is also related to former issues #812 and #814.
- Allow that UNRST produced by INTERSECT have undefined PHASES flag in INTEHEAD, ans assume that oil/wat/gas are always present 
- Fix a special INTERSECT issue/bug where the ACTNUM in the EGRID files does not match the number of properties. So, similar to #807, will now use PORV to decide on active cells. The culprit is that is assumes that a INIT file with same name is present; for practical purposes it is shall be OK in 99%.

Intersect restart issues

---

src/xtgeo/xyz/_xyz_roxapi.py

For writing a Points (dataframe) to RMS with attributes, more than 3 wells were required; otherwise no attributes were written back. This is now corrected.

BUG: correct threshold on dataframe length wrt attrs

---

docs/history.md
src/xtgeo/cube/_cube_roxapi.py
src/xtgeo/grid3d/_grid_roxapi.py
src/xtgeo/grid3d/_gridprop_roxapi.py
src/xtgeo/grid3d/grid.py
src/xtgeo/plot/baseplot.py
src/xtgeo/roxutils/roxutils.py
src/xtgeo/surface/_regsurf_export.py
src/xtgeo/surface/regular_surface.py
src/xtgeo/xyz/points.py
tests/test_grid3d/test_grid3d_deprecations.py
tests/test_surface/test_deprecation.py

Remove tests and code that was marked for deprecation in version 3.
Also limit Roxar API to version 1.5 and above (this is inherently given that python 3.6 is not longer supported in XTGeo; since Roxar API version up to 1.4 is solely in python 3.6).

Version 3 part2

---

tests/test_grid3d/test_grid3d_deprecations.py

Fixup: The code says deprecation in version 4.0, but the tests triggered error in version 3.0

FIX: a few tests failed wrongly on deprecation in 4.0

---

requirements/pyproject.toml.komodo
requirements/requirements.txt
requirements/requirements_dev.txt
src/xtgeo/grid3d/_grid_roxapi.py
src/xtgeo/grid3d/_gridprop_lowlevel.py
src/xtgeo/grid3d/grid.py
src/xtgeo/surface/_regsurf_grid3d.py
src/xtgeo/surface/_regsurf_oper.py
tests/test_common/test_numpy.py
tests/test_surface/test_regular_surface.py

It appears that using order="K" in numpy.ravel() and numpy.ma.ravel() is prone to problems. Rather be spesific on required order ("F" or "C"). Cf. issue #861 
By improving code, the restrictions set on numpy version 1.24.3 can be removed.

FIX: improve use of "order" in np.ravel()

---

.github/workflows/build_docs.yml
.github/workflows/ci-test-xtgeo-cibuildwheel.yml
.github/workflows/linting.yml
.github/workflows/test.yml
README.md
pyproject.toml
requirements/pyproject.toml.komodo
requirements/requirements_dev.txt
requirements/requirements_dev_rms.txt
requirements/requirements_setup.txt
setup.py

- `wheel` 0.30 - <0.38 has a security vulnerability Snyk ranks as High
- Python 3.7 reaches EOL on June 26 2023, some dependencies (ecl-data-io) have already dropped support

BLD: Pin wheel>=0.38, drop Python 3.7

---

src/xtgeo/roxutils/roxutils.py
tests/test_roxarapi/test_roxarapi_reek.py

Since roxar.Project points to _roxar.Project for RMS <= 13 and to _rmsapi.Project for RMS > 13, there is no need to refer to private package og module import

FIX: replace import of private module _roxar

---

src/xtgeo/grid3d/_find_gridprop_in_eclrun.py
tests/test_grid3d/test_grid_specialcases.py

Solves #874 
It seems that a restart (UNRST) is not always is starting with `SEQNUM` (which was the assumption) but may start with `TNAVHEAD`. This PR fix that issue, but does not solve if there may be other similar corner cases.

Fix ecl read issues

---

docs/usextgeoroxar.rst
src/xtgeo/surface/_regsurf_oper.py
src/xtgeo/surface/regular_surface.py
src/xtgeo/xyz/_xyz.py
src/xtgeo/xyz/_xyz_oper.py
tests/test_surface/test_regular_surface_in_other.py
tests/test_xyz/test_points_poly.py

[ENH: improve points in polygons methods](https://github.com/equinor/xtgeo/pull/877/commits/2369745837fecdf23268ca78183fb7ff20cc3c2f) 
Improve both speed and logics. Speed by using MPath from matplotlib,
and logics to adress the strange behaviour in previous versions, when
e.g. ovelaping polygons areas gets cumulated values.
[ENH: improve speed for surf vs polygons operations](https://github.com/equinor/xtgeo/pull/877/commits/14a93c703b1f7fc3d4c1b1a6a4a0be7d488a1cee) 
Replace  internal methods with matplotlib MPath for surface
vs polygons operations. When many points in the polygons, the
speed improvement is magnitude of orders!
In contrast the points in polygons, the 'add_inside()' etc methods
works as before, hence the ``_version`` key is marked
intentionally as private

Improve points etc in polygons operations

---

src/xtgeo/surface/_regsurf_export.py
src/xtgeo/surface/_regsurf_roxapi.py
src/xtgeo/surface/regular_surface.py
tests/test_roxarapi/test_roxarapi_reek.py
tests/test_surface/test_regular_surface.py

As default, the numpy (masked) array is stored as 64 bit numpy, in line with Roxar API storage. Here it is allowed to cast to 32 bit in import. The methods surface_from_grid() and surface_from_cube() Still lack dtype, but it is easy to set with the property srf.dtype = ...

ENH: allow RegularSurface() store np.float32 values

---

pyproject.toml
setup.py

setuptools-scm 8.0.1 seems to have issues with the version file being provided through the old setup.py function.

Move setuptools-scm configuration to pyproject.toml

---

pyproject.toml

BLD: pin tables < 3.9 for python 3.8

---

pyproject.toml
src/clib/CMakeLists.txt

This removes the cmake policies and defers more to CMake to find and add the numpy headers-- I guess we don't need special RHEL6 handling for that anymore.
This also adds the installation directory to be configurable from pyproject.toml. Maybe we could consider installing the compiled module to just `xtgeo._cxtgeo` rather than nesting into `xtgeo.cxtgeo._cxtgeo`?
Resolves #901

Simplify CMakeLists

---

tests/test_grid3d/gridprop_generator.py

After the hypothesis profile change a test that generates a GridProperty started to fail reliably.
```sh
FAILED tests/test_grid3d/test_grid_properties.py::test_gridproperties_from_roff - ValueError: Requested keyword NA<< is not in ROFF file, valid entries are [], set strict=False to warn instead.
```
It seems like it might be timing related: drawing the name value outside of the GridProperty instantiation seems to fix it.

TST: fix hypothesis test failure

---

.gitignore
src/xtgeo/grid3d/_roff_grid.py

Resolves #895 
Me and @ErichSuter worked on this together, we looked at the doc. strings, to the best of our knowledge they look right. But an extra pair of eyes wound not hurt.

CLN: Add typing to roff_grid

---

src/xtgeo/grid3d/_grid3d_utils.py
src/xtgeo/grid3d/_gridprops_import_roff.py
src/xtgeo/grid3d/grid_properties.py
tests/test_grid3d/test_grid_properties.py

Resolves #939
This test failure is caused by
https://github.com/equinor/xtgeo/blob/69d8caadb48ed1a6d359612bdb9e5b5282e2f7f3/src/clib/xtg/grd3d_scan_roffbinary.c#L367-L373
This will ignore any properties starting with "NA", which is probably not what we want. This PR changes to scan keywords with roffio instead, at a minor performance hit. We could probably seek to replace the C scan with roffio completely, but the `GridProperties.scan_keywords()` method has a return format that roffio cannot support.
Benchmarks:
- xtgeo-testdata/1/geogrid.roff
- roffio: 0.013
- cxtgeo: 0.003
- xtgeo-testdata/2/geogrid.roff
- roffio: 0.013
- cxtgeo: 0.003
- xtgeo-testdata/3/valysar.roff
- roffio: 0.013
- cxtgeo: 0.003

Scan keywords with roffio when importing GridProperties

---

.pylintrc
src/xtgeo/well/_well_oper.py
src/xtgeo/xyz/_xyz_data.py
tests/test_well/test_well_vs_grid.py

Fix a bug where the recent Well() refactor gets wrong log_record codes

---

src/xtgeo/common/sys.py
tests/test_common/test_system.py

Also does some minor refactoring, particularly to the initialization function.
Resolves #897

Add typing to `common.sys`

---

src/xtgeo/grid3d/grid_property.py

BUG: fix typo introduced in function call

---

src/xtgeo/well/_well_roxapi.py
src/xtgeo/well/well1.py
tests/test_roxarapi/test_roxarapi_reek.py

Closing #884 
This aim with this PR is to make it possible to append selected well logs to the RMS icons. It will potentially speed up execution a lot when multiple wells with multiple logs.
The PR do also some refactoring and simplification in the `_well_roxapi.py` module, but no complete attempt on `mypy` typing, which can be a separate PR.

ENH: add key update_option for Well to roxar

---

src/xtgeo/__init__.py
src/xtgeo/plot/__init__.py
src/xtgeo/plot/baseplot.py
src/xtgeo/plot/grid3d_slice.py
src/xtgeo/plot/xsection.py
src/xtgeo/plot/xtmap.py
src/xtgeo/surface/_regsurf_oper.py
src/xtgeo/xyz/_xyz_oper.py
tests/test_plot/test_matplotlib_import.py

Edit: Apparently you can just set the backend in an environment variable. We can set a deprecation notice for `xtgeo.plot` next.
~~This might be a terrible way to do this -- I am not sure. We should deprecate using matplotlib/xtgeo.plot entirely if possible with xtgeo 4.0.~~
~~Normally dynamically importing modules is fairly straight forward: you can just import them in the function or method they are used in. However, by default matplotlib will look for display settings on the machine it's being run on and compute cluster nodes do not have this set.~~
~~The suggested solution to this is to import matplotlib before anything else is imported, and set its backend to `use("Agg")` which doesn't look for display information. This must be done before matplotlib does _anything_ else. xtgeo …

CLN: Dynamically import matplotlib and pyplot

---

tests/test_opm_integration/test_gridprop_io.py

Resolves #996 
These tests fail intermittently for a number of reasons. Sometimes segfaulting, sometimes FileNotFound or ValueError, sometimes results differ. These issues do not necessarily appear to be a result of xtgeo but should maybe be looked at more closely.
Will investigate a bit further still since it might be something to report to OPM.

TST: xfail flaky OPM tests

---

src/xtgeo/surface/_regsurf_gridding.py
src/xtgeo/surface/regular_surface.py
tests/test_surface/test_regular_surface.py

PR that adds a gaussian filter method to the existing `smooth()` function for RegularSurfaces, and rewrites the existing  `smooth()` function to handle surfaces that includes undefined values. 
- The `scipy.ndimage` functions used for the filtering does not handle np.nan or masked values in a proper manner which leads to undesired results. 
- To overcome this limitation the surface is filled first before smoothing is applied, and subsequently the original mask is restored on the smoothed output.
Resolves #916

Add gaussian smoothing method for `RegularSurface` and improve smoothing on surfaces with undefined values.

---

ci/testkomodo.sh

The script that enables the RMS environment currently enables Komodo stable by default and has some subtleties that we should probably address before testing against it in this way.

CI: Don't test against RMS environments

---

mypy.ini
pyproject.toml
src/clib/cxtgeo_fake.py

This PR marks a significant step in refining our `mypy` settings, specifically for the `xtgeo/grid3d` directory. The journey revealed some surprising insights into how `mypy` interprets the `ignore_missing_imports` setting.
- Introduced finer-grained control over `mypy` settings for individual files in `xtgeo/grid3d`.
- Removed `ignore_missing_imports` from the global settings in `mypy.ini`.
Initially, it was assumed that `ignore_missing_imports = True` would only affect third-party imports. However, it became evident that this setting also led to imports from our module being treated as `Any`. This was highlighted in the following proof of concept:
```python
from enum import Enum, unique
from xtgeo.grid3d._ecl_output_file import Phases
@unique
class Cod(Enum):
atlantic = 0
pacific = 1 …
```

TST: Update mypy settings - ignore errors file in xtgeo/grid3d

---

mypy.ini
src/xtgeo/common/xtgeo_dialog.py
src/xtgeo/grid3d/grid_property.py

numpy typing has some peculiarities with dtypes; where `x: np.dtype`/`np.dtype[Any]` resolves as a class but the `np.float32` and the like resolve as types. So some explicitness was used for the dtypes.

CLN: Update GridProperty typing

---

src/clib/xtg/surf_get_z_from_xy.c

CLN: Fix uninitialized variable in surf_get_z_from_xy.c

---

src/xtgeo/grid3d/grid_property.py

Even with future annotations imported creating a unioned type of types, using the `type[]` future annotations, caused some errors running mypy under Python 3.8.

FIX: Union dtypes for Python 3.8 compatibility

---

src/xtgeo/__init__.py
src/xtgeo/plot/__init__.py

This also removes the default top-level import so a deprecation warning is not issued on _all_ xtgeo usage.
Resolves #573

DEP: Issue deprecation warning for `xtgeo.plot`

---

mypy.ini
src/xtgeo/__init__.py
src/xtgeo/grid3d/_grid3d_fence.py
src/xtgeo/grid3d/grid.py

Reordered imports in `xtgeo.__init__ ` to avoid circular imports.
- grid related imports are now imported before surface related imports

CLN: Add types to grid3d_fence

---

src/clib/xtg/grdcp3d_get_vtk_esg_geometry_data.c

Remove unused variable in grdcp3d_get_vtk_esg_geometry_data.c ( related to # 904).

CLN: Remove unused variable in grdcp3d_get_vtk_esg_geometry_data.c

---

src/xtgeo/grid3d/_grid3d_fence.py
src/xtgeo/grid3d/grid.py

In the `xtgeo.Grid.get_randomline()` function, having `hincrement` argument as a bool or a number together with a Polygon as `fencespec` triggered a bug. 
This PR fixes that, and removes the option to have `hincrement` as a bool to make the input more clear for users.
resolves #1040

BUG: fix issue with get_randomline when using Polygons

---

src/clib/xtg/except.c
src/clib/xtg/grd3d_points_ijk_cells.c
src/clib/xtg/grdcp3d_get_vtk_esg_geometry_data.c

This is related to #904.
There are still macOS-related tasks left in #904.

CLN: In C-code: Remove unused function, init variable and fix 'strncpy maxlen'

---

src/xtgeo/cube/cube1.py

This functionality is better handled by using segyio and we should direct users to it instead.
Resolves #1072

DEP: Add deprecation notice for segy scanning

---

src/xtgeo/__init__.py
src/xtgeo/cube/__init__.py
src/xtgeo/grid3d/__init__.py
src/xtgeo/grid3d/_gridprop_import_eclrun.py
src/xtgeo/grid3d/_gridprops_import_eclrun.py
src/xtgeo/grid3d/_gridprops_import_roff.py
src/xtgeo/grid3d/grid_properties.py
tests/test_grid3d/test_gridprops_list_properties.py

Resolves #1084
This function helps to replace the now-deprecated `scan_keywords` static method. It can be used to get a list of grid properties within a roff file or within an Eclipse init (static properties) or restart (dynamic properties) file.

ENH: Add `list_gridproperties` function

---

src/xtgeo/grid3d/grid_properties.py

Resolves #608 
This should follow #1092 so its replacement function is present.

DEP: Deprecate GridProperties.scan_keywords

---

src/xtgeo/__init__.py

We can skip generating plots for them and also handle them separately, making the test-linux job a bit clearer.
Resolves #1105

FIX: use mpl agg backend across OSs without display

---

docs/xtgeo_4_migration.md
src/xtgeo/grid3d/_grid_roxapi.py
src/xtgeo/grid3d/grid.py

The `dimensions_only` argument available in `xtgeo.grid_from_roxar()`  does not work, and this PR resolves #1042. 
Its intended use of this argument was to create a grid with correct dimensions that could be used as a template for a new GridProperty. By only extracting the dimensions of a grid, the users could get a performance increase.
Extracting dimensions from a grid is pretty straightforward with the roxar API, hence this bug will not be fixed.
This PR adds a deprecation warning to the `dimensions_only` argument, and removes all code related to this argument since  `dimensions_only=True` did not work anyway.
- the deprecation warning is intended for users that tried setting  `dimensions_only=True` but instead set it to   `dimensions_only=False` when they got an error message

DEP: Deprecate dimension_only argument in `grid_from_roxar()`

---

.github/workflows/publish.yml

This makes use of PyPI trusted publisher mechanism which is more secure and absolves the need for a PyPI token.
This still needs to be tested and potentially adjusted depending on how ci build wheel works.
Resolves #947

CI: Publish wheels with trusted publisher

---

mypy.ini
src/xtgeo/grid3d/_gridprop_export.py
src/xtgeo/grid3d/grid_property.py

These functions did not support memory streams which made _only_ typing them not possible. Some changes needed to be made to support writing and appending to streams as well.
Adds to #1011

CLN: Refactor and type `_gridprop_export`

---

src/xtgeo/xyz/_xyz_roxapi.py
src/xtgeo/xyz/points.py
tests/test_roxarapi/test_roxarapi_reek.py
tests/test_xyz/test_xyz_roxapi_mock.py

PR that adds the support of reading `well_picks` from RMS as `xtgeo.Points`, and writing them back. Closes #1108 
- Support well_picks of type "fault" and "horizon" - specified through the category argument
- no support of "zone" picks yet, it requires a bit more work as it needs entry and exit values for MD/TVD/X/Y.
- Support reading well pick attributes. 
- Support creation of user defined attributes and modifying regular (non read-only) attribute values
- Create well pick set if not present in the project upon export
Also some refactoring of existing code was performed:
- Created separate functions for common functionality between roxar.well_picks and roxar.Points import/export. e.g applying pfilter or replacing undefined values in the dataframe
- Simplified and merged identical …

ENH: Roxar well picks support

---

.github/workflows/publish.yml

This functionality seems to have changed with v4 where artifacts must now be given a unique name.

CI: Upload uniquely named artifacts

---

.gitignore
src/lib/CMakeLists.txt
src/lib/include/xtgeo/xtgeo.h
src/lib/src/grid3d/cellvol.cpp
src/xtgeo/grid3d/_grid_etc1.py
tests/test_grid3d/test_grid.py

Allows for a more Pythonic way of working on the Python side. No change in performance
tests/test_grid3d/test_grid.py::test_benchmark_bulkvol
Before:
```sh
------------------------------------------------- benchmark 'bulkvol': 1 tests ------------------------------------------------
Name (time in us)               Min       Max      Mean   StdDev    Median      IQR  Outliers  OPS (Kops/s)  Rounds  Iterations
-------------------------------------------------------------------------------------------------------------------------------
test_benchmark_bulkvol     639.5000  786.2080  654.6035  15.0888  648.2500  20.5520    117;15        1.5276     821           1
------------------------------------------------------------------------------------------------------------------------------- …
```

CLN: Create and return bulkvol array from C++

---

tests/test_cube/test_cube_deprecations.py
tests/test_grid3d/test_grid_ecl_grid.py

`pytest.warns(None)` was deprecated with pytest 8.0. Additionally I think pytest has an error with respect to catch the `test_cube_from_file_warns` `DeprecationWarning` and does a wrong instantiation of a DeprecationWarning to catch it. The message specificity was removed because if `from_file()` is deprecated then by definition so is any additional arguments that method takes.

TST: Fix tests broken with pytest 8.0

---

pyproject.toml
src/xtgeo/__init__.py
src/xtgeo/grid3d/_roff_parameter.py
tests/test_plot/test_matplotlib_import.py

Resolves #794
Resolves #1145
This should receive a simpler fix once `xtgeo.plot` is fully deprecated. This backend handling should then be pushed upstream to xtgeoviz, cf https://github.com/equinor/xtgeoviz/issues/34.
Changing mpl configuration should be restricted to running on RGS machines to the greatest degree possible, and only when relevant to do so.
This also sets explicit exports from the top-level package with `__all__`, which should help type checking but needs pruning with xtgeo 4: https://github.com/equinor/xtgeo/issues/1150

FIX: Set mpl backend to Agg in Linux only

---

.github/workflows/test.yml
conftest.py

We do not need to use a gui method of plotting for test runs, and other backends may fail on CI.
The previous solution of setting the environment variable did not work: despite numerous other ways of setting this, Windows seems to ignore it and continues to use TkAgg over Agg, causing sporadic failures in CI.

TST: Set MPLBACKEND=Agg on test invocations

---

src/xtgeo/surface/regular_surface.py
tests/test_surface/test_file_io.py

If too few active map nodes, less than 4, a warning will be given when `to_file()` is called. In addition a new key `error_if_near_empty` is added, and if this is True, an error will be raised in stead.
Closes #797

ENH: issue warning or error if output surface is empty or near empty

---

src/xtgeo/surface/_regsurf_boundary.py
src/xtgeo/xyz/_polygons_oper.py
tests/test_surface/test_regular_surface.py

PR to address #1160. 
After changing to using shapely to create boundary polygons for surfaces in #1140, it seems shapely in some cases fails to create the polygons. Leading to the "POLY_ID" error which derives from an empty polygon and hence an empty dataframe.
This PR should add more robustness to the boundary polygons method by:
1. Added noding of the linestrings before running the polygonize function to handle potensial crossing lines. See https://github.com/shapely/shapely/issues/1736
2. Fixing a bug that sometimes created small triangular polygons along the boundary. This cleans up the dataset before running the shapely polygonize function. (This was the case for our complex test case, hence some adjustment was needed there.) 
-    <img …

FIX: Inrease robustness in boundary polygons

---

docs/tutorial/examples_rms.rst
src/xtgeo/grid3d/_grid_boundary.py
src/xtgeo/grid3d/_grid_etc1.py
src/xtgeo/grid3d/grid.py
tests/test_grid3d/test_grid_operations.py

PR which resolves #925 and adds a new method `grid.get_boundary_polygons()` for extracting boundary polygons from a grid instance.
Key notes:
- kept same signature as the `surf.get_boundary_polygons()` except added an optional `filter_array` argument for defining a specific part of the grid that the boundary should be extracted from e.g. a region or around specific conditions.
- estimates an appropriate alpha value using the xinc and yinc from the grid.
- to speed up performance the xy points are averaged over layers in the grid to reduce number of points before doing the triangulation.
- added caching of the `grid.get_xyz()`,  `grid.get_dx()` and `grid.get_dy()` to speed up performance when the method is run multiple times in loop with different filter_array input (e.g. looping over and …

ENH: Add grid boundary polygons

---

src/xtgeo/grid3d/_gridprop_value_init.py
tests/test_grid3d/test_grid_property.py

Resolves #1115 
When a GridProperty was created with values of an unsupported type it would try to return `_values`, which was unbound due to being unhandled.

FIX: Raise on bad GridProperty values

---

src/xtgeo/cube/cube1.py
tests/test_cube/test_cube.py

Resolves #1178 
Notably this does not work with streams -- but it never did and requires a larger refactor in order to do so. Fixing that is probably not worth while for code that will soon be deprecated.

FIX: Ensure cube scanning paths are strings

---

docs/xtgeo_4_migration.md

Resolves #1144 
It could have been unclear how xtgeo.plot could be deprecated alongside a recommendation to import `xtgeo.plot` directly.

DOC: Clarify `xtgeo.plot` text

---

.github/workflows/publish.yml

CI: Remove MacOS latest xlarge runner

---

.github/workflows/test.yml
src/lib/include/xtgeo/grid3d.hpp
src/lib/src/grid3d/grid.cpp
src/xtgeo/grid3d/_grid_etc1.py
src/xtgeo/grid3d/grid.py
tests/test_grid3d/test_grid.py

This is a PR to address an urgent need in am ongoing top-prioritized project, where current solutions using numpy operations combined with existing `xtgeo` functionality become too memory demanding. The C++ function here in this PR will solve this in a much more lean and memory and CPU friendly manner. 
There is also a commit that modifies the macos tests. They fail initially due installation issues with pytables and HDF5.

ENH: add Grid() function get_heights_above_ffl.

---

.github/workflows/publish.yml

There are recurrent problems on building on Macos, which are hard to debug. Need a quite rapid release and propose to skip Mac OS wheels for now.

BLD: skip macos builds for CIBW and publish

---

src/xtgeo/grid3d/_grid_etc1.py
src/xtgeo/grid3d/_grid_wellzone.py
src/xtgeo/well/_well_io.py
src/xtgeo/xyz/_xyz_data.py
src/xtgeo/xyz/_xyz_io.py
src/xtgeo/xyz/_xyz_oper.py
tests/test_roxarapi/test_roxarapi_reek.py
tests/test_surface/test_forks.py
tests/test_well/test_well.py

Resolves #1216 
Reduces the number of warnings from 4000 to 1500. The remaining ones are mostly self-emitted for xtgeo 4.0 deprecations, with a few numpy ones.
A big-looking change is the removal of `inplace=` arguments. See the commit comment for a longer description, but tl;dr this didn't actually do things inplace but on a copy internally. See https://github.com/pandas-dev/pandas/pull/51466

TST: Fix various warnings emitted from tests

---

.github/workflows/test.yml

Needed to reopen #1239 
This PR tries to solve this matter by just disabling `--generate-plots` when running windows-latest in Github actions.

CI: skip --generate-plots on windows due to random TCL install errors

---

examples/multiprocess_surfs.py
tests/test_surface/test_forks.py

The described problem is Windows Python 3.12 test timeouts #1229 but it appears to occur randomly.  This solution is a bit of a "fumbling in the dark, and cross fingers".
Propose:
1. Timeouts in the actual tests
2. Change surface_from_file() to use pure python code, not "cxtgeo". It *may* be that the C binding are causing the issues we see here.

CI: propose timeout in forks and pure python i/o for test robustness

---

src/xtgeo/__init__.py
src/xtgeo/cube/_cube_roxapi.py
src/xtgeo/grid3d/_grid_roxapi.py
src/xtgeo/grid3d/_gridprop_roxapi.py
src/xtgeo/roxutils/_roxar_loader.py
src/xtgeo/roxutils/_roxutils_etc.py
src/xtgeo/roxutils/roxutils.py
src/xtgeo/surface/_regsurf_roxapi.py
src/xtgeo/well/_blockedwell_roxapi.py
src/xtgeo/xyz/_xyz_roxapi.py
tests/test_roxarapi/test_roxarapi_reek.py

Closes #1258 
This would allow to import `rmsapi as roxar` when present, i.e. alias it to `roxar` without `DeprecationWarning`.
I have kept the wording `roxar`, although it may be more optimal at a later stage to refer to `rmsapi`. However this will also trigger a debate if e.g. `xtgeo.surface_from_roxar()` should be replaced with `xtgeo.surface_from_rmsapi()` or `...rms()`. But we can take that later.

MAINT: resolve import roxar vs import rmsapi

---

.github/workflows/test.yml
examples/grid3d_prop_as_map.py
src/lib/CMakeLists.txt
src/lib/include/xtgeo/geometry.hpp
src/lib/include/xtgeo/grid3d.hpp
src/lib/include/xtgeo/numerics.hpp
src/lib/include/xtgeo/regsurf.hpp
src/lib/src/common/geometry/interpolate.cpp
src/lib/src/common/geometry/volumes.cpp
src/lib/src/cube/cube.cpp
src/lib/src/grid3d/cell.cpp
src/lib/src/init.cpp
src/lib/src/regsurf/sample_grid3d.cpp
src/xtgeo/grid3d/_grid3d_fence.py
src/xtgeo/surface/_regsurf_grid3d.py
src/xtgeo/surface/regular_surface.py
tests/test_internal/test_cell_grid3d.py
tests/test_internal/test_regsurf.py
tests/test_surface/test_regular_surface_vs_grd3d.py

Closes #1262 
* Refactor some C++ vectors with known length to be of type `std::array` instead of `std::vector`. In particular the function that receives the corner coordinates, which has fixed length 24. In a future change, we should consider `structs` in stead
* Alllow top and base and indexes to be returned in the same call
*  Avoid recomputing corner coordinates
* Add OMP pragma for parallel processing (in the first implemention for Linux only)
In a concrete case I have, these changes will in effect change the execution for HC thickness maps fram 4-5 minutes to 10 seconds

ENH: optimize speed for surface_from_grid method

---

.github/workflows/test.yml
src/lib/src/regsurf/sample_grid3d.cpp
src/lib/src/regsurf/utilities.cpp

The custom logger made in C++ which applies python's logging is probably too fragile when multithreaded and/or nested calls, and usage is removed for now in the codebase (although keep the class/function until a better solution)
This links to #1262

FIX: remove calls to custom logger in c++ code and revert "big" ci test

---

src/xtgeo/xyz/_xyz_oper.py

This came after an ad-hoc  debugging of a user request; the user that got non-sensible errors when running `xtgeoviz` plotting. 
After debugging, it was found that the error was not in `xtgeoviz`, but in `xtgeo`, and it seems to be triggered in some corner cases (perhaps rarely?).
The first error was a numpy reshape error (due to wrong order of assigning a dataframe after that dataframe actually may in some cases change length), and the second was that concatination of dataframes sometimes leads
to columns getting type `object` in stead of a numerical datatype.

BUG: fix inconsistencies is XYZ dataframes

---

.github/workflows/publish.yml
.github/workflows/test.yml
src/lib/numpy.i

Resolves #1269 
1. SWIG 4.3.0 was released, causing the numpy bindings to need updating else compiling fails.
2. brew `pkg-config` was renamed to `pkgconf` but macOS GH Runners are imaged with pkg-config.

BLD: Update numpy.i, CI: unlink deprecated pkg-config in macOS

---

.github/workflows/publish.yml
.github/workflows/test.yml

Resolves #1272
GitHub has updated their macOS images to install pkgconf over pkg-config.

CI: Revert macOS runner pkg-config work-around

---

pyproject.toml
src/lib/numpy.i

Resolves #1275
We can unpin swig once we drop support for Python 3.8 and move forward with #1233

Revert numpy.i changes, pin swig<4.3.0

---

src/xtgeo/grid3d/_gridprop_export.py
tests/test_grid3d/test_grid_property.py

Closes #1279 
Note: It could also be possible to let the user input this value, but that will be a larger change. I propose we add this a patch now and consider future improvements later.
Related to this is also the use of the `isdiscrete` property and `dtype` option in the `to_file()` appears unclear for me now. Perhaps a need for a deeper look into this at some point.

BUG: undef values in grdecl export shall be 0 or 1

---

src/xtgeo/well/_well_roxapi.py

BUG: fix well export to rms for masked numpy with Nan

---

.github/workflows/mypy.yml
.github/workflows/publish.yml
.github/workflows/test.yml
README.md
pyproject.toml
src/xtgeo/grid3d/_ecl_inte_head.py
src/xtgeo/grid3d/_grid_etc1.py
src/xtgeo/grid3d/_roff_parameter.py
tests/test_grid3d/test_grdecl_format.py
tests/test_grid3d/test_grid_grdecl.py
tests/test_grid3d/test_grid_property.py
tests/test_grid3d/test_grid_roff.py

This PR replaces #1233 
Resolves https://github.com/equinor/xtgeo/issues/1209
This unpins numpy<2 and builds the SWIG C library against numpy >= 2.0.0. Versions of numpy major 2 are backward compatible with numpy 1 with respect to the C api. Hence we should not see issues in environments where numpy<2 may be maintained for years to come, i.e. RMS environments.
The numpy SWIG bindings committed in this repository are not out-of-date in a way that would break compatibility. The last update to them in numpy's repository was two years ago from the time of this commit.
The PR has been manually tested with RMS 14.2, which applies python 3.11 and numpy==1.24.
As a consequence of supporting numpy>=2 this PR deprecates support for Python 3.8, which hits EOL on October 2024.

BLD: Unpin numpy 2 

---

.github/workflows/test.yml
pyproject.toml
src/xtgeo/grid3d/_grid3d_utils.py
src/xtgeo/grid3d/_grid_etc1.py
src/xtgeo/grid3d/_gridprop_lowlevel.py
src/xtgeo/grid3d/grid.py
src/xtgeo/xyz/_xyz_io.py
src/xtgeo/xyz/points.py
tests/test_grid3d/test_ecl_inte_head.py
tests/test_grid3d/test_grdecl_format.py
tests/test_opm_integration/test_gridprop_io.py

CI: overwrite with RMS package versions

---

.github/workflows/publish.yml

Resolves #1100
GitHub Actions originally did not publish macOS arm64 runners with Python 3.9 and said they had no intention to. They seem to have reversed on this decision and (apparently) do.

BLD: Publish for macOS Python 3.9

---

ci/testrmsenv.sh

Resolves part of https://github.com/equinor/rms-sys/issues/267
Added a bash script that can be run from the github workflows to execute the xtgeo unit tests towards and RMS Python Enviroment. Note that the xtgeo-testdata files needed to run the tests are cached on the github actions runner, so pointing to the path XTGEO_TESTDATA_PATH with the cached data should be sufficient to run the tests.
The script copies the required test files, installs the test dependencies and and runs the pytests.

CI: Add script for running tests from github worklow

---

src/xtgeo/surface/_regsurf_export.py

Seems that taken yflip into account when exporting Irap binary/ascii was missing.

BUG: re-activate yflip on Irap export

---

src/xtgeo/common/_xyz_enum.py
src/xtgeo/xyz/_xyz.py
src/xtgeo/xyz/_xyz_io.py
src/xtgeo/xyz/_xyz_roxapi.py
src/xtgeo/xyz/points.py
src/xtgeo/xyz/polygons.py
tests/test_xyz/test_points.py
tests/test_xyz/test_polygon.py
tests/test_xyz/test_xyz_roxapi_mock.py

Closes #900
Polygons from RMS can now be read including attributes. Note that the current RMSAPI do not allow for storing attributes back to RMS, and also there are no (known) file formats for Polygons that supports attributes. As a workaround, one can use CVS  files to both read and write Polygons Pandas dataframes with attributes.
In addition several "fixups" on more consistent usage of Enum's in the code.

ENH: add attributes for Polygons when reading RMS

---

src/xtgeo/grid3d/grid.py
tests/test_grid3d/test_grid.py
tests/test_grid3d/test_grid_operations.py

Closes #1327 
Use zone property codes if they are available when calling `grid.subgrids_from_zoneprop` method

ENH: Utilize grid property  codes when using grid.subgrids_from_zoneprop method

---

.github/workflows/publish.yml
.github/workflows/test.yml
pyproject.toml
src/xtgeo/well/_well_io.py

BLD: add support for python 3.13

---

docs/api-grids.rst
docs/api-well.rst

Add documentation for a few useful class functions 
- xtgeo.create_box_grid
- xtgeo.grid_from_cube
- xtgeo.grid_from_surfaces
- xtgeo.wells_from_files

Add missing documentation for some class functions
